### ISSUE TITLE
Doesn't work with `vite@2.6.0` (`import_meta.glob is not a function`)

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#156]

**Comment by brillout** [comment]
`2.6.0` breaks `vite-plugin-ssr` (`import_meta.glob is not a function` when `import.meta.glob` lives in `node_modules/`).

The problem is on Vite's side.

Until there is a fix, pin Vite to `2.5.10`.

**Comment by OfekA** [comment]
@brillout For some reason I still get this error when running the `vue-full` example, am I doing something wrong? here is my package.json:

```json
{
  "scripts": {
    "start": "npm run dev",
    "dev": "ts-node ./server",
    "prod": "npm run build && npm run prod:serve",
    "// Build for production": "",
    "build": "npm run build:clean && npm run build:vite && npm run build:prerender",
    "build:clean": "rimraf dist/",
    "build:vite": "vite build && vite build --ssr",
    "build:prerender": "vite-plugin-ssr prerender",
    "// Static serve for production": "",
    "prod:serve": "serve dist/client/ --listen 3000"
  },
  "dependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^16.9.3",
    "@types/node-fetch": "^3.0.2",
    "@vitejs/plugin-vue": "^1.8.0",
    "@vue/compiler-sfc": "3.2.12",
    "@vue/server-renderer": "3.2.12",
    "express": "^4.17.1",
    "node-fetch": "^2.6.1",
    "rimraf": "^3.0.2",
    "serve": "^12.0.1",
    "ts-node": "^10.2.1",
    "typescript": "^4.4.3",
    "vite": "2.5.10",
    "vite-plugin-md": "^0.11.1",
    "vite-plugin-ssr": "0.3.3",
    "vue": "3.2.12"
  }
}
```

**Comment by brillout** [comment]
@OfekA What does `cat node_modules/vite/package.json | grep version` say?

**Comment by brillout** [comment]
@ everyone: it may take some while until there is Vite fixes this. Let me know if you need `vite@2.6.0` and I'll push.

**Comment by OfekA** [comment]
@brillout 
```
➜ cat node_modules/vite/package.json | grep version
  "version": "2.5.10",
```

**Comment by brillout** [comment]
@OfekA Does `rm -r dirst/ node_modules/.vite/` fix it? Note that I cannot reproduce the error with `vue-full` so I'm thinking you probably have some cache holding `vite@2.6.0` artifacts.

**Comment by OfekA** [comment]
Thanks @brillout, I deleted all installed modules and reinstalled them and it fixed the issue 🙏

**Comment by brillout** [comment]
Fix released in `vite-plugin-ssr@0.3.5`.

**Comment by brillout** [comment]
And fix for Client Router (`import { useClientRouter } from 'vite-plugin-ssr/client/router`) released in `0.3.6`.

**Comment by brillout** [comment]
`0.3.7` &mdash; there was a bug in the Client Router fix.

**Comment by brillout** [comment]
All tests are now passing, so `0.3.7` is good.
